-- MySQL Script generated by MySQL Workbench
-- Tue May 30 22:49:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_codigo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_codigo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_codigo` DEFAULT CHARACTER SET utf8 ;
USE `db_codigo` ;

-- -----------------------------------------------------
-- Table `db_codigo`.`tbl_alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`tbl_alumno` (
  `alumno_id` INT NOT NULL AUTO_INCREMENT,
  `alumno_dni` VARCHAR(20) NOT NULL,
  `alumno_nombre` VARCHAR(255) NOT NULL,
  `alumno_email` VARCHAR(100) NULL,
  PRIMARY KEY (`alumno_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo`.`tbl_bootcamp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`tbl_bootcamp` (
  `bootcamp_id` INT NOT NULL AUTO_INCREMENT,
  `bootcamp_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`bootcamp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo`.`tbl_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`tbl_modulo` (
  `modulo_id` INT NOT NULL AUTO_INCREMENT,
  `modulo_nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`modulo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo`.`tbl_matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`tbl_matricula` (
  `matricula_id` INT NOT NULL AUTO_INCREMENT,
  `matricula_grupo` VARCHAR(20) NOT NULL,
  `alumno_id` INT NOT NULL,
  `bootcamp_id` INT NOT NULL,
  PRIMARY KEY (`matricula_id`),
  CONSTRAINT `fk_tbl_matricula_tbl_alumno`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `db_codigo`.`tbl_alumno` (`alumno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_matricula_tbl_bootcamp1`
    FOREIGN KEY (`bootcamp_id`)
    REFERENCES `db_codigo`.`tbl_bootcamp` (`bootcamp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo`.`tbl_matricula_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`tbl_matricula_modulo` (
  `matricula_modulo_id` INT NOT NULL AUTO_INCREMENT,
  `matricula_modulo_nota` INT NOT NULL DEFAULT 0,
  `matricula_id` INT NOT NULL,
  `modulo_id` INT NOT NULL,
  PRIMARY KEY (`matricula_modulo_id`),
  CONSTRAINT `fk_tbl_matricula_modulo_tbl_matricula1`
    FOREIGN KEY (`matricula_id`)
    REFERENCES `db_codigo`.`tbl_matricula` (`matricula_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_matricula_modulo_tbl_modulo1`
    FOREIGN KEY (`modulo_id`)
    REFERENCES `db_codigo`.`tbl_modulo` (`modulo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
