# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    container_name: api.mysql
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: codigo2023
      MYSQL_DATABASE: db_pos
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: