version : '3.3'

services:
  api:
      build: .
      image: img-api-udemy:1.0
      env_file:
        - ./.env
      ports:
        - "5000:5000"

  nginx:
      container_name: api.proxy
      image: img-nginx-udemy:1.0
      build : ./nginx
      volumes:
        - ./src/static:/usr/src/static
        - media_volume:/usr/src/media
      ports:
        - "8090:80"
      depends_on:
        - api

volumes:
  static_volume:
  media_volume: