export const INICIO_CARGANDO_MESAS = 'INICIO_CARGANDO_MESAS';
export const FIN_CARGANDO_MESAS = 'FIN_CARGANDO_MESAS';
export const SET_MESAS = 'SET_MESAS';
export const SET_SELECCIONAR_MESA = 'SET_SELECCIONAR_MESA';

export const INICIO_CARGANDO_CATEGORIAS = 'INICIO_CARGANDO_CATEGORIAS';
export const FIN_CARGANDO_CATEGORIAS = 'FIN_CARGANDO_CATEGORIAS';
export const SET_CATEGORIAS = 'SET_CATEGORIAS';
export const SET_SELECCIONAR_CATEGORIA = 'SET_SELECCIONAR_CATEGORIA';

export const INICIO_CARGANDO_PLATOS_POR_CATEGORIA =
	'INICIO_CARGANDO_PLATOS_POR_CATEGORIA';
export const FIN_CARGANDO_PLATOS_POR_CATEGORIA =
	'FIN_CARGANDO_PLATOS_POR_CATEGORIA';
export const SET_PLATOS_POR_CATEGORIA = 'SET_PLATOS_POR_CATEGORIA';

export const AGREGAR_PLATO_A_PEDIDO = 'AGREGAR_PLATO_A_PEDIDO';
export const RESTAR_PLATO_A_PEDIDO = 'RESTAR_PLATO_A_PEDIDO';

export const ELIMINAR_PEDIDO = 'ELIMINAR_PEDIDO';

export const INICIO_CARGANDO_LOGIN = 'INICIO_CARGANDO_LOGIN';
export const FIN_CARGANDO_LOGIN = 'FIN_CARGANDO_LOGIN';
export const SET_SUCCESS_LOGIN = 'SET_SUCCESS_LOGIN';

export const INICIO_CARGANDO_PLATOS = 'INICIO_CARGANDO_PLATOS';
export const SET_PLATOS = 'SET_PLATOS';
export const FIN_CARGANDO_PLATOS = 'FIN_CARGANDO_PLATOS';

export const INICIO_CARGANDO_PEDIDOS_DB = 'INICIO_CARGANDO_PEDIDOS_DB';
export const SET_PEDIDOS_DB = 'SET_PEDIDOS_DB';
export const FIN_CARGANDO_PEDIDOS_DB = 'FIN_CARGANDO_PEDIDOS_DB';
